version: '3.9'

services:
  fastapi:
    build: backend/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: backend
    restart: always

  streamlit:
    build: frontend/
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: frontend
    restart: always

networks:
  deploy_network:
    driver: bridge

